// Generated by CoffeeScript 1.7.1
var c, callback, progress;

c = new WebGLRobots.DefaultCanvas('#hubo_container');

window.hubo = new Hubo('hubo2', callback = function() {
  c.add(hubo);
  return $('#load').hide();
}, progress = function(step, total, node) {
  return $('#load').html("Loading " + step + "/" + total);
});

$('#mouse_info_dialog').dialog({
  autoOpen: false,
  closeOnEscape: true,
  buttons: {
    OK: function() {
      return $(this).dialog('close');
    }
  }
});

$('#mouse_info_button').on('click', function() {
  return $('#mouse_info_dialog').dialog('open');
});
