hold on
% Triangle
line([universal_point(1) neck1tip_point(1)] ...
    ,[universal_point(2) neck1tip_point(2)] ...
    ,[universal_point(3) neck1tip_point(3)] ...
    ,'Color','black')
line([universal_point(1) neck2tip_point(1)] ...
    ,[universal_point(2) neck2tip_point(2)] ...
    ,[universal_point(3) neck2tip_point(3)] ...
    ,'Color','black')
line([neck1tip_point(1) neck2tip_point(1)] ...
    ,[neck1tip_point(2) neck2tip_point(2)] ...
    ,[neck1tip_point(3) neck2tip_point(3)] ...
    ,'Color','black')
% Linear actuators
line([neck1base_point(1) neck1tip_point(1)] ...
    ,[neck1base_point(2) neck1tip_point(2)] ...
    ,[neck1base_point(3) neck1tip_point(3)] ...
    ,'Color','green')
line([neck2base_point(1) neck2tip_point(1)] ...
    ,[neck2base_point(2) neck2tip_point(2)] ...
    ,[neck2base_point(3) neck2tip_point(3)] ...
    ,'Color','red')
