function [fitresult, gof] = createFit(NK1, NK2, Zp)
%CREATEFIT1(NK1,NK2,ZP)
%  Create a fit.
%
%  Data for 'Linear Fit' fit:
%      X Input : NK1
%      Y Input : NK2
%      Z Output: Zp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jul-2013 16:36:51


%% Fit: 'Linear Fit'.
[xData, yData, zData] = prepareSurfaceData( NK1, NK2, Zp );

% Set up fittype and options.
ft = fittype( 'poly11' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Linear Fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Linear Fit', 'Zp vs. NK1, NK2', 'Location', 'NorthEast' );
% Label axes
xlabel( 'NK1' );
ylabel( 'NK2' );
zlabel( 'Zp' );
grid on
view( 19.5, 42 );

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, [xData, yData], zData, 'Style', 'Residual' );
legend( h, 'Linear Fit - residuals', 'Location', 'NorthEast' );
% Label axes
xlabel( 'NK1' );
ylabel( 'NK2' );
zlabel( 'Zp' );
grid on
view( 19.5, 42 );


