// Generated by CoffeeScript 1.7.1
var c, callback, progress;

c = new WebGLRobots.DefaultCanvas('#hubo_container');

window.hubo = new Hubo('hubo2', callback = function() {
  c.add(hubo);
  $('#load').hide();
  c.projector = new THREE.Projector();
  return $(c.renderer.domElement).on("mousedown", function(event) {
    var click, intersects, raycaster, vector;
    click = {};
    click.x = event.clientX - $(this).offset().left;
    click.y = event.clientY - $(this).offset().top;
    vector = new THREE.Vector3((click.x / c.display_width) * 2 - 1, -(click.y / c.display_height) * 2 + 1, 0.5);
    c.projector.unprojectVector(vector, c.camera);
    raycaster = new THREE.Raycaster(c.camera.position, vector.sub(c.camera.position).normalize());
    intersects = raycaster.intersectObjects(Array(hubo.links.Body_Torso), true);
    if (intersects.length > 0) {
      hubo.unhighlightAll();
      $('#part').html(intersects[0].object.parent.name);
      return intersects[0].object.parent.highlight();
    }
  });
}, progress = function(step, total, node) {
  return $('#load').html("Loading " + step + "/" + total);
});

$('#mouse_info_dialog').dialog({
  autoOpen: false,
  closeOnEscape: true,
  buttons: {
    OK: function() {
      return $(this).dialog('close');
    }
  }
});

$('#mouse_info_button').on('click', function() {
  return $('#mouse_info_dialog').dialog('open');
});
