// Generated by CoffeeScript undefined
var c, callback, hubo, makeSlider, sign;

c = new WebGLRobots.DefaultCanvas("#hubo_container");

hubo = new WebGLRobots.Robot();

hubo.loadURDF("" + local_root + "data/hubo-urdf/model.urdf", callback = function() {
  c.add(hubo);
  return $(".joint").each(function() {
    var id, lower, upper;
    id = $(this).attr("data-name");
    $("[data-name=" + id + "] .joint_txt").html("0.00");
    console.log("makeSlider " + id);
    console.log("id: " + id + " lower: " + hubo.joints[id].lower_limit + " upper:" + hubo.joints[id].upper_limit);
    console.log(typeof hubo.joints[id].lower_limit);
    lower = parseFloat(hubo.joints[id].lower_limit);
    upper = parseFloat(hubo.joints[id].upper_limit);
    return makeSlider($("[data-name=" + id + "] .joint_slider"), id, lower, upper);
  });
});

makeSlider = function(el, id, minval, maxval) {
  var s;
  s = el;
  s.slider({
    min: minval,
    max: maxval,
    step: 0.01,
    value: 0
  });
  s.on("slide", function(event, ui) {
    return $("[data-name=" + id + "] .joint_txt").html(ui.value.toFixed(2));
  });
  return s.on("slide", function(event, ui) {
    return hubo.joints[id].value = ui.value;
  });
};

sign = function(x) {
  if (x) {
    if (x < 0) {
      return -1;
    } else {
      return 1;
    }
  } else {
    return 0;
  }
};
